---

- name: 5.Mise à jour du cache apt si un repo ou une clé a été ajouté.
  apt: 
    update_cache: yes
    cache_valid_time: 3600
  when: docker_apt_repo_result.changed or docker_apt_key_result.changed
