---
paquets_communs:
   - apt-transport-https
   - ca-certificates
   - curl

pc_architecture: "{{ lookup('pipe', 'dpkg --print-architecture') }}"

docker_sources:

  - "deb [arch={{ pc_architecture }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"

docker_repo_gpg_key_url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
