---

- name: 2.Installer DotDeb repo pour Debian ou Ubuntu.

  apt_repository: repo="{{ item }}"

  with_items: "{{ dotdeb_sources_Debian if ansible_distribution == 'Debian' else dotdeb_sources_Ubuntu }}"

  register: dotdeb_apt_repo_result
